#!/bin/sh

WORKFLOW_PATH="/Users/$USER/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows"

if target_dir="`linkwf \"$1\"`"; then 
    cd "$target_dir"
else
    cd "$WORKFLOW_PATH"
fi
