#!/bin/sh

current_dir="`dirname $0`"
source $current_dir/lib/const.sh

get_plist_value() {
    value="`$PLIST -c \"Print $1\" \"$2\" 2>/dev/null`"
}

CMD="linkwf:"

if [ -n "$1" ];
then
    current_bundle_id="$1"
    current_name="$1"
else
    if [ ! -f "$INFO_PLIST" ];
    then
        echo "$CMD Please provides workflow name/bundleid or info.plist file"
        exit -1
    fi
    get_plist_value "bundleid" "$INFO_PLIST"
    current_bundle_id="$value"
    get_plist_value "name" "$INFO_PLIST"
    current_name="$value"
fi

cd "$WORKFLOW_PATH" 

wf_list=()

for wf in */ ;
do
    wf_list+=("$WORKFLOW_PATH/$wf")
done

cd - > /dev/null

for ((i = 0; i < ${#wf_list[@]}; i++))
do
    plist="${wf_list[$i]}/$INFO_PLIST"
    get_plist_value "bundleid" "$plist"
    bundle_id="$value"
    get_plist_value "name" "$plist"
    name="$value"
    if [ "$current_bundle_id" == "$bundle_id" -o "$current_name" == "$name" ];
    then
        echo "${wf_list[$i]}"
        exit 0
    fi
done

echo "$CMD Can't find workflow associated with current directory"
exit -1



