#!/bin/sh

current_dir="`dirname $0`"
source $current_dir/lib/const.sh

OPTIND=1
usage() {
    echo "usage: $CMD -gp [-f] [-n] [-o rsync-options] [name/bundleid] "
    exit 0
}
get=false
put=false
confirm=true
options="-av --update  --delete --exclude=.*"
dryrun=false
while getopts "hngpo:" opt
do
    case $opt in
        h)
            usage
            ;;
        g)  
            get=true
            ;;
        p) 
            put=true
            ;;
        o) 
            options="$OPTARG"
            ;;
        n)
            dryrun=true
            ;;
        \?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if ! $get && ! $put ; then
    echo "$CMD: Neither -g nor -p be selected, exiting..."
    exit -1
fi

search_word="$1"
if target_dir="`findwf \"$search_word\"`"; then  
    :
elif [ -n "$search_word" ]; then
    echo "$CMD can't find workflow"
    exit -1
else
    read line
    target_dir="$line"
    if [ ! -d "$target_dir" ];
    then
        echo "$CMD can't find workflow"
        exit -1
    fi
fi

if $dryrun; then
    options+=" -n"
fi

if $confirm; then
    if $get && $put; then 
        msg= "Sync content between: `pwd` and $target_dir"
    elif $get; then
        msg="Copy content from $target_dir to `pwd`"
    elif $put; then
        msg="Copy content from `pwd` to $target_dir"
    fi
    read -p "$CMD: $msg with option \"$options\", continue? [y/n]" -n 1 -r reply
    echo
    if [[ ! $reply =~ [yY] ]]; then
        exit -1
    fi
fi

sync_folder() {
    rsync $options "$1" "$2"
}


if $put; then
    sync_folder "./" "$target_dir"
fi

if $get; then
    sync_folder "$target_dir" "./"
fi

