#!/bin/sh

CMD="syncwf"

OPTIND=1
usage() {
    echo "usage: $POMPT [-g] [-p] [-n] -o [override rsync options] [name/bundleid] "
    exit 0
}
get=false
put=false
confirm=true
options="-av --update  --delete --exclude=.*"
dryrun=false
while getopts "hngpo:" opt
do
    case $opt in
        h)
            usage
            ;;
        g)  
            get=true
            ;;
        p) 
            put=true
            ;;
        o) 
            options="$OPTARG"
            ;;
        n)
            dryrun=true
            ;;
        \?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if ! $get && ! $put ; then
    usage
fi

search_word="$1"
if target_dir="`linkwf \"$search_word\"`"; then  
    :
elif [ -n "$search_word" ]; then
    echo "$CMD can't find workflow"
    exit -1
else
    read line
    target_dir="$line"
    if [ ! -d "$target_dir" ];
    then
        echo "$CMD can't find workflow"
        exit -1
    fi
fi

if $dryrun; then
    options+=" -n"
fi

if $confirm; then
    read -p "$CMD: sync content between: `pwd` and $target_dir with option \"$options\", continue? [y/n]" -n 1 -r reply
    echo
    if [[ ! $reply =~ [yY] ]]; then
        exit -1
    fi
fi

sync_folder() {
    rsync $options "$1" "$2"
}

if $get; then
    sync_folder "$target_dir" "./"
fi

if $put; then
    sync_folder "./" "$target_dir"
fi
