#!/bin/sh

CMD="syncwf"

OPTIND=1
usage() {
    echo "usage: $POMPT [-r] [-f] [name/bundleid] "
    exit 0
}
reverse=false
confirm=true
while getopts "hrf" opt
do
    case $opt in
        h)
            usage
            ;;
        r)  
            reverse=true
            ;;
        f) 
            confirm=false
            ;;
        \?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))


search_word="$1"

if target_dir="`linkwf \"$search_word\"`"; then  
    :
elif [ -n "$search_word" ]; then
    echo "$CMD can't find workflow"
    exit -1
else
    read line
    target_dir="$line"
    if [ ! -d "$target_dir" ];
    then
        echo "$CMD can't find workflow"
        exit -1
    fi
fi

if $confirm; then
    read -p "$CMD: sync content between: `pwd` and $target_dir, continue? [y/n]" -n 1 -r reply
    if [[ ! $reply =~ [yY] ]]; then
        echo
        exit -1
    fi

fi

if $reverse; then
    rsync -av --update  --delete --exclude '.*' "$target_dir" ./
    rsync -av --update  --delete --exclude '.*' ./ "$target_dir"
else
    rsync -av --update  --delete --exclude '.*' ./ "$target_dir"
    rsync -av --update  --delete --exclude '.*' "$target_dir" ./
fi


